language: java
jdk:
- oraclejdk8

services:
  - mongodb

notifications:
  email:
    recipients:
    - ross@mongodb.com
    on_success: change
    on_failure: always
  flowdock:
    secure: "Ziw1Be2tV0QAYuiYDrepfdNH/oBfNhnXFMji3AdRi6MePVpc6CtOOT/b9Fra\nQgMMrX3AHk/QIDo6QQx9/aVB3FS1fzOPGQkSsEZmiljZU7wZCct1sSSyttf/\nsRG0lyTnmgFNTHyTSDT3JbXAkyF/vJmG/JJJoBUZhmFxzR2fM0Q="

branches:
  only:
  - master
  - 1.0.x

env:
  global:
    - TERM=dumb

script:
  - ./gradlew -q assemble
  - ./gradlew check -i -S
