baseurl = "/mongo-java-driver-rx/1.1"
languageCode = "en-us"
title = "MongoDB RxJava Driver"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true

# Update versions in mongodb.toml as well
[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "/javadoc"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/mongodb/mongo-java-driver-rx/tree/1.0.x"
